services:
  dropadox:
    build:
      context: .
      target: prod   # <- change this only
    container_name: dropadox
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./local.db:/usr/src/app/local.db
      - ./uploads:/usr/src/app/uploads
    working_dir: /usr/src/app
    env_file:
      - ./.env
