services: 
  dropadox:
      image: node:22-alpine
      container_name: dropadox
      restart: always
      ports:
        - "3000:3000"
      volumes:
        - ./:/usr/src/app
      working_dir: /usr/src/app
      env_file:
        - ./.env
      #for prod build 
      #command: sh -c "npm install && npm run build && node .output/server/index.mjs"
      

      #init db if none 
      command: sh -c ' 
        npm install &&
        if [ "$APP_MODE" = "prod" ]; then
          npm run build && node .output/server/index.mjs;
        elif [ "$APP_MODE" = "init-dev" ]; then
          npx drizzle-kit generate &&
          npx drizzle-kit migrate &&
          npm run dev;
        else
          npm run dev;
        fi
      '
     

      #id db already exist and has bin initalized
      #command: sh -c "npm install && npm run dev"
      
